# list of the analyzers to be called by lookoutd
analyzers:
  - name: style-analyzer
    addr: ipv4://localhost:9930
    disabled: false
    # feedback: url to link in the comment_footer. For example, to open a new GitHub issue
    # settings: map with custom info that will be sent to the analyzer "as is"

providers:
  github:
    comment_footer: '_If you have feedback about this comment, please, [tell us](%s)._'
    # The minimum watch interval to discover new pull requests and push events
    watch_min_interval: 2s
    # Authorization with GitHub App

    # https://github.com/apps/lookout-demo
    app_id: 24491
    private_key: /compose-files/lookout-demo.2019-01-30.private-key.pem

    # See https://developer.github.com/apps/building-github-apps/authenticating-with-github-apps/
    # app_id: 1234
    # private_key: ./key.pem
    # installation_sync_interval: 1h
    #
    # GitHub App OAuth credentials
    # client_id:
    # client_secret:

# web interface configuration, only available if authorizing with GitHub App
web:
  # Secret key to sign JSON Web Tokens
  signing_key:

# These are the default timeout values. A value of 0 means no timeout
timeout:
  # Timeout for an analyzer to reply a NotifyReviewEvent
  analyzer_review: 0
  # Timeout for an analyzer to reply a NotifyPushEvent
  analyzer_push: 0
  # Timeout for an HTTP requests to the GitHub API
  github_request: 5m
  # Timeout for Git fetch actions
  git_fetch: 20m
  # Timeout for Bblfsh to reply a Parse request
  bblfsh_parse: 5m
